### ISSUE TITLE
在混合模式下如果二级菜单路由没有，则侧边栏隐藏

### ISSUE THREAD

**Issue by peak520** [stepui/stepin-template-js#7]
<img width="654" alt="1681810702311" src="https://user-images.githubusercontent.com/51201793/232739701-677f37b2-d835-441e-91fc-8945d47eb243.png">

**Comment by iczer** [comment]
功能已更新，更新组件库 stepin 至 `2.1.33-beta` 即可：
```bash
yarn add stepin
```
